name: Build2 WarZ_Server.sln

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2013
      run: |
        echo "Setting up Visual Studio 2013..."
        choco install visualstudio2013community

    - name: Build Solution with VS2013
      run: |
        echo "Building solution with Visual Studio 2013..."
        "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" "$(System.DefaultWorkingDirectory)/server/src/WarZ_Server.sln" /Build "Release"
