name: Build WarZ_Server.sln

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Visual Studio 2013 ISO
      run: |
        curl -L -o vs2013.iso "https://archive.org/download/en_visual_studio_community_2013_with_update_5_x86_dvd_6816332/en_visual_studio_community_2013_with_update_5_x86_dvd_6816332.iso"

    - name: Mount ISO
      run: |
        PowerShell Mount-DiskImage -ImagePath $(System.DefaultWorkingDirectory)\vs2013.iso

    - name: Install Visual Studio 2013
      run: |
        start /wait D:\setup.exe /Q

    - name: Build Solution with VS2013
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" "$(System.DefaultWorkingDirectory)/server/src/WarZ_Server.sln" /Build "Release"
